default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: odinbook_development

test:
  <<: *default
  database: odinbook_test

production:
  <<: *default
  database: <%= ENV["ODINBOOK_DB_NAME"] %>
  username: <%= ENV["ODINBOOK_DB_USER"] %>
  password: <%= ENV["ODINBOOK_DB_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
  